### ISSUE TITLE
Mods I make to HAP values

### ISSUE THREAD

**Issue by Colorado4Wheeler** [webdeck/homebridge-indigo-packager#1]
Changes to homebridge/hap-nodejs/lib/gen/HomeKitTypes.js that I make to support what the actual world is like.  The temp ranges are excessive but it covers any situaton.

ColorTemperature: extend max value to 15000 to support actual Kelvin ranges
CurrentTemperature: change range from -1000 to 1000, current values are worthless for outside temps
RemainingDuration and SetDuration: Changed from a ridiculous 5 minute duration (3600) to 43200

**Comment by webdeck** [comment]
Oh, I didn't realize you were changing hap-nodejs.  That's an upstream project of homebridge.  The best thing to do is to have me set those on the accessory instances instead of changing the accessory classes themselves.  I can update any properties on a characteristic.  For example:

this.service.getCharacteristic(Characteristic.CurrentTemperature).setProps({minValue: -1000, maxValue:1000})

So, all we need to do is agree upon how to include properties in your JSON characteristic responses and I will update those property values in homebridge-indigo2.  Go ahead and open an issue on that project with the updated JSON format proposal and we can discuss there.
